### ISSUE TITLE
Bump sci-libs/roc* to last version 3.5.0/3.5.1

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#152]
Please bump sci-libs/roc* to last version 3.5.0/3.5.1

PS. I will attemp compile sci-libs/roc* 3.5.0/1.

Success with many, but rocALUTION need fix CMakeLists.txt to same as etalon CMakeLists.txt from rocFFT. And I stupid on it.

https://github.com/perestoronin/rocmnew/blob/master/sci-libs/rocALUTION/

https://github.com/perestoronin/rocmnew/blob/master/sci-libs/rocFFT/

Please fix export DEVICE_LIB_PATH="/usr/lib64" to export DEVICE_LIB_PATH="/usr/lib" because in /usr/lib rocm-device-lib store all *.bc files. It may be need fix rocm-device-lib to store DEVICE_LIB in more suitable path other than /usr/lib either usr/lib64 ? For example in path /usr/lib/hip/3.5/lib ?

**Comment by justxi** [comment]
@perestoronin  
About the bitcode files... Yes that is a good point... I am currently thinking about that too... 

Due to the fact that the files are installed by "rocm-device-libs", which is an ebuild already in portage, I would like to involve @candrews ... 
AMD is installing to the library directory of the compiler... in our case it would be "/usr/lib/llvm/roc/lib" and "/usr/lib/llvm/roc/lib/libdevice". I remember that the bitcode files in some AMD projects are also stored in "/usr/lib/bitcode". On my system "/usr/lib" is a link to "/usr/lib64". Due to the fact that my understanding of these directories are the 32 and 64-bit libraries of the operating system, these are not the ideal location. Furthermore, the AOMP compiler from AMD searches automatically for bitcodes files in "[clang bin dir]/../lib" and "[clang bin dir]/../lib/libdevice". As far as I know... the bitcode files are only used by clang... that would be an argument for putting them in the llvm/clang directories... on the other hand... does it make sense to put them under a specific version of the compiler? Ok, currently we have only one version of llvm-roc, but I think we all hope that we can use the system llvm/clang in the future... So something like "/usr/lib[64]/rocm-device-libs" or "/usr/lib[64]/rocm-device-libs/bitcode" seems to be the best compromise.

**Comment by perestoronin** [comment]
> @perestoronin
> About the bitcode files... Yes that is a good point... I am currently thinking about that too...
 What is your opinion?

I liked path ended with "bitcode". For example /usr/lib/llvm/roc/3.5/lib/bitcode ?

Also I think about relocate hip (based rocclr) to other more suitable path. For example to /usr/lib/hip/roc/3.5 ?

**Comment by justxi** [comment]
To move the bitcode files in directory ending with "bitcode" would be my first choice. Let wait what @candres thinks about it.

Due to the fact, that I think HIP has only one dependency (rocclr) it is ok to keep "/usr/lib/hip/3.5"... as long as we can not install two ROCm version side by side, we could omit the version number also.

**Comment by perestoronin** [comment]
fixed hipCUB to compile with hipcc in commit https://github.com/perestoronin/rocmnew/commit/af663480398d96f68f7d0d2a28993f1eb764d27c

**Comment by justxi** [comment]
It would be nice I you could create a PR, then it´s easier to add your work.

**Comment by perestoronin** [comment]
With this https://github.com/perestoronin/rocmnew/blob/master/sys-devel/hip/files/hip-3.5.1-hip_vector_types.patch all libraries was compiled by hipcc.

**Comment by justxi** [comment]
Ok, thank you, I will apply your patch.

**Comment by justxi** [comment]
Ok, this fixed some problems, but "rocBLAS" fails on my system when building with tensile.

**Comment by perestoronin** [comment]
I use separate https://github.com/perestoronin/rocmnew/tree/master/dev-util/Tensile version 3.5.0
And use them in building of problem rocBLAS, look at ebuild https://github.com/perestoronin/rocmnew/tree/master/sci-libs/rocBLAS how to over.

**Comment by implr** [comment]
> On my system "/usr/lib" is a link to "/usr/lib64".

On systems which completed the [17.1 profile migration](https://gentoo.org/support/news-items/2019-06-05-amd64-17-1-profiles-are-now-stable.html) that symlink is removed, breaking hipcc.
If you don't plan to move the files to bitcode/ as you said above, it'd be really nice if you could change the path to /usr/lib/ to unbreak the ebuilds for now.

**Comment by justxi** [comment]
ok

**Comment by justxi** [comment]
@littlewu2508 I see that you updated a few ebuilds. 
Did you manage to build "rocBLAS" 3.5, thats where I stopped?
If yes, would you like to create PRs?

**Comment by littlewu2508** [comment]
> @littlewu2508 I see that you updated a few ebuilds.
> Did you manage to build "rocBLAS" 3.5, thats where I stopped?
> If yes, would you like to create PRs?

Yes, I've successfully build rocBLAS 3.5 with tensile on gentoo prefix. I plan to create PRs after another commit very soon.

Currently I'm helping  Benda Xu (heroxbd@gentoo.org) deploy ROCm on gentoo prefix, and I find the easiest way is to base on your repo. So my updates are mainly about prefixfication of the newest ebuilds (v3.5.0).

This PR will contain many modifications of ebuilds and a few patches for prefixfication, some of which non-trivial and may cause hidden problems. I'd like to open a new issue for prefixfication

**Comment by justxi** [comment]
@littlewu2508 
Ok, I try your changes regarding rocBLAS.

The gentoo prefix projects sounds interesting.

Thanks, I will wait for your new issue and PR regarding prefixfication.

**Comment by justxi** [comment]
@littlewu2508 

> Currently I'm helping Benda Xu ([heroxbd@gentoo.org](mailto:heroxbd@gentoo.org)) deploy ROCm on gentoo prefix, and I find the easiest way is to base on your repo. So my updates are mainly about prefixfication of the newest ebuilds (v3.5.0).

That means ROCm will become part of the official Gentoo protage tree?
Or is there a separate repository for Gentoo prefix?

**Comment by littlewu2508** [comment]
> 
> 
> @littlewu2508
> 
> > Currently I'm helping Benda Xu ([heroxbd@gentoo.org](mailto:heroxbd@gentoo.org)) deploy ROCm on gentoo prefix, and I find the easiest way is to base on your repo. So my updates are mainly about prefixfication of the newest ebuilds (v3.5.0).
> 
> That means ROCm will become part of the official Gentoo protage tree?
> Or is there a separate repository for Gentoo prefix?

We're planning to merge these ebuild into official Gentoo protage tree.
More details [here](https://github.com/justxi/rocm/issues/8#issuecomment-672687417)

**Comment by justxi** [comment]
I think the bump to 3.5.1 is mostly done and further discussion will follow in "PRs to Gentoo", I close this.
