### ISSUE TITLE
clinfo segfaulting by passing corrupt pointer to Clang

### ISSUE THREAD

**Issue by awenocur** [justxi/rocm#24]
clinfo is segfaulting when I call it

libamdocl is passing a pointer to uninitialized memory to clang::ASTReader::ReadVersionTuple via a call to clang::CompilerInstance::ExecuteAction

I'm seeing this with the build for rocm-opencl-runtime-2.0.0, as I'm not able to make 2.1.0 build just yet.

I'll add details as I investigate; this might be an upstream problem, but I'm not seeing it on Ubuntu, which currently leads me to believe it's due to packaging.

**Comment by justxi** [comment]
rocm-opencl-runtime-2.0.0 seems to have some problems, I don´t think that it is an upstream problem, because the "old" or previous ebuild "media-libs/ROCm-OpenCL-Runtime" ebuild works (for me).

But if you have detail information about the problem described by you, please report, then we can find a solution and improve the ebuild.

**Comment by bluescarni** [comment]
Just FYI, it is not only ``clinfo`` which is segfaulting for me. I tried a few examples from the Boost.Compute opencl library and they are also segfaulting, while they used to work fine with earlier versions of the opencl runtime ebuild (the one with the different name). I am using the 2.1 version of the stack at the moment.

**Comment by awenocur** [comment]
Thus far, I've rebuilt llvm-roc and with -O0 and -ggdb with a Debug build of rocm-opencl-runtime.

The clang:: namespace within libamdocl64.so is not being symbolicated with DWARF, despite both packages being rebuilt; the amd:: and other namespaces are. Is it possible that the wrong LLVM is being statically linked here? I'll try rebuilding the installed Clang static libraries symbolicated to see whether that results in the symbols showing up in libamdocl64.so

**Comment by justxi** [comment]
Can you provide you ebuilds. I observed that building "media-libs/ROCm-OpenCL-Runtime" takes a lot more time then build "sys-devel/llvm-roc" and "dev-libs/rocm-opencl-runtime" together. Furthermore, the resulting "libamdocl64.so" seems to be much smaler when building with "dev-libs/rocm-opencl-runtime". But this could be due to dynamically linked libraries(?).

**Comment by awenocur** [comment]
OK; I can add a few gists for my modified ebulds to enable DWARF symbolication.

What I'm observing now is that my changes have resulted in different behavior from the statically linked llvm_roc library. Instead of passing a pointer to uninitialized memory, it's causing an assertion to fail. So at least I now know this is something the developers anticipated might happen. I guess this is due to the -DNDEBUG flag being disabled and not the DWARF symbols, though.

``clinfo: /var/tmp/portage/sys-devel/llvm-roc-2.0.0/work/llvm-roc-2.0.0/include/llvm/ADT/SmallVector.h:160: const T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::operator[](llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type) const [with T = long unsigned int; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::const_reference = const long unsigned int&; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type = long unsigned int]: Assertion `idx < size()' failed.``

I'm still haven't figured out where these clang:: symbols are originating, that are being statically linked into libamdocl64.so, so still don't have lines of code for them.

**Comment by awenocur** [comment]
https://gist.github.com/awenocur/f08ba89923a6282c7111c446a6f02ee4
https://gist.github.com/awenocur/45bc56bb7b1edbb106929e3b68b8ca73
https://gist.github.com/awenocur/bc4a25c1b774376de9b23a47c68a0e4c

**Comment by kpande** [comment]
managed to make 2.1.0 build using the 'new' ebuilds but saw the same segfault here. tried reverting to 2.0.0, same result. the 'old' ebuild works.

**Comment by justxi** [comment]
Maybe I have an idea... I added  "link_directories(/usr/lib/llvm/roc-2.0.0/lib)" with "rocm-opencl-runtime-2.0.0-add-paths.patch", because I got a lot of missing libraries, e.g. "-lclang*". But I could not remember that these libraries are used when using the ebuild "media-libs/ROCm-OpenCL-Runtime". So I think also, that this must be linking problem. It seems the libraries of "llvm-roc" are not correctly added, because I think in the "media-libs/ROCm-OpenCL-Runtime" ebuild there are a lot of "*.a" libraries which are statically linked into "libamdocl64.so".

**Comment by justxi** [comment]
@kpande Sounds good, thanks for the feedback.

**Comment by awenocur** [comment]
so I'm seeing an out of range error where LLVM is subscripting a list of arguments on line 97 of /usr/lib/llvm/roc-2.0.0/include/llvm/Option/Arg.h, which is causing the corrupted pointer to be passed when this assertion is absent

The call is originating from a source tree in /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/ROCm-OpenCL-Runtime-roc-2.0.0/compiler/driver/src/, specifically /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/ROCm-OpenCL-Runtime-roc-2.0.0/compiler/driver/src/driver/AmdCompiler.cpp:1076

This is a call to generate LLVM bytecode with options {"-cl-kernel-arg-info", "-cl-std=CL1.2", "-O3", "-mcpu=gfx803", "-D__OPENCL_VERSION__=120", "-Xclang", "-cl-ext=+cl_khr_fp64,+cl_khr_global_int32_base_atomics,+cl_khr_global_int32_extended_atomics,+cl_khr_local_int32_base_atomics,+cl_khr_local_int32_extended_atomics,+cl_khr_int64_base_atomics,+cl_khr_in"..., "-mllvm", "-amdgpu-early-inline-all", "-mllvm", "-amdgpu-prelink", "-include-pch", "/tmp/AMD_24506_1/t_24506_2", "-Xclang", "-fno-validate-pch", "-Xclang", "-target-feature", "-Xclang", "-code-object-v3"}

A few levels up on the stack, this all originates within amd::Runtime::init() on line 221 of /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/ROCm-OpenCL-Runtime-roc-2.0.0/api/opencl/amdocl/cl_icd.cpp

**Comment by awenocur** [comment]
I wonder if there are Clang static libs being linked in that are including headers from another LLVM installation here.

**Comment by awenocur** [comment]
I managed to make 2.1.0 build. It's acting exactly the same, apart from some source files having different line numbers.
SmallVector.h is still showing the problem at line 160
The line in AmdCompiler.cpp for generating the LLVM bitcode moved to line 1065.
The line in cl_icd.cpp initializing the runtime is still 221.

**Comment by justxi** [comment]
Did you test the resulting library?
Does "clinfo" give expected results?

**Comment by kpande** [comment]
they mention it segfaults, too. I guess that means clinfo did not work - for what it's worth, the -9999 git build for the old Thunk stuff was ancient, using `drm-next-wip` branch that hadn't been updated in ~10 months. using git master allowed multiple GPUs to work. I'm sure there's probably some old dependency being pulled in here, too.

**Comment by justxi** [comment]
Does the segfault occur also, whenn "media-libs/ROCm-OpenCL-Runtime" is used to build "amdocl64.so" ?

Besides this, due to the fact that the llvm/clang from ROC is necessary to build the amdocl64.so and not all changes are upstreamed yet, it is needed to build both for each new version of ROCm. I think currently it doesn´t make sense to split the ebuild. So the ebuild "media-libs/ROCm-OpenCL-Runtime"  should be preferred because it is known to work. But I will keep track of ROCm and try so solve the problems in the meantime.

**Comment by davidrohr** [comment]
I finally installed a AMD card. clinfo does not segfault, but running clinfo shows the following error:
=== CL_PROGRAM_BUILD_LOG ===
: error: undefined symbol: get_global_id
>>> referenced by /tmp/t_9557_33-06a3c4.o:(sum)

: error: undefined symbol: get_global_id
>>> referenced by /tmp/t_9557_33-06a3c4.o:(sum)
Error: Creating the executable from LLVM IRs failed.
  Preferred work group size multiple              <getWGsizes:1200: create kernel : error -46>

Apparently the clang that was compiled doesn't uinderstand get_global_id

**Comment by justxi** [comment]
Then I have to check the build files from ROCm-OpenCL-Runtime regarding the build process. 
Which ebuild did you use?

**Comment by davidrohr** [comment]
rocm-opencl-runtime-2.2.0.ebuild

**Comment by justxi** [comment]
Ok, interessting. "get_global_id" seems to be part of "ROCm-Device-Libs" (https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/issues/58)

**Comment by davidrohr** [comment]
This could also be some kind of incompatibility between clinfo and the
clang that comes with ROCm.
Clang does not include the opencl headers by default, while most other
opencl compilers do.
Without the headers, get_global_id would not be defined.

Am 25.03.19 um 21:49 schrieb Wilfried Holzke:

**Comment by justxi** [comment]
"get_global_id" is in "opencl-c.h" as part of the llvm/clang project https://clang.llvm.org/doxygen/opencl-c_8h_source.html. This file is included in the build process. But maybe it is not linked to the resulting libamdocl64.so(?).

**Comment by davidrohr** [comment]
What is the general status of that ebuild? Is it working for you?

**Comment by awenocur** [comment]
Right now, for ROCm 2.2, it's building the ROC LLVM libraries for me, but the OpenCL Runtime isn't finding them when linking.

**Comment by davidrohr** [comment]
@awenocur : I had the same issue and added "-L /usr/lib/llvm/roc*/lib" manually to the linker

**Comment by awenocur** [comment]
Did you do that via -DCMAKE_CPP_FLAGS in the ebuild itself?

**Comment by justxi** [comment]
@davidrohr  Interesstingly last time it builds, but running clinfo segfaults. Due to the fact that the "old" ebuild (media-libs/ROCm-OpenCL-Runtime) produces a usable libamdocl64.so, I have to find the difference. Besides the missing library include path which you mentioned above, there must be something else wrong.

**Comment by davidrohr** [comment]
OK, from my side I'll also try media-libs/ROCm-OpenCL-Runtime and see if this gives the same error

**Comment by justxi** [comment]
Did you try "media-libs/ROCm-OpenCL-Runtime"?

**Comment by davidrohr** [comment]
not yet, it is on my agenda...

**Comment by justxi** [comment]
There are ebuilds for ROCm 2.3 now. And ROCm-OpenCL-Runtime (dev-libs/rocm-opencl-runtime-2.3.0) builds faster on my system compared to ROCm 2.2.

**Comment by davidrohr** [comment]
@justxi : I have now tried media-libs/ROCm-OpenCL-Runtime (2.3.9999) and that works correctly.
Could you check the repository, you mentioned there was a new release rocm-opencl-runtime based on ROCm-OpenCL-Runtime, but I cannot find it. Also, I'd prefer a 2.3.0 instead of the 9999 to have a stable state.

**Comment by awenocur** [comment]
Could you elaborate on how the Clang dependencies are linked, now?

I currently have only Clang 7.0.1 installed, but CMake is finding Clang 9.0.0, prior to building any new Clang.

I then see: `CMake Error at compiler/llvm/tools/clang/CMakeLists.txt:477 (message):
  Cannot disable static analyzer while enabling ARCMT or Z3`

**Comment by justxi** [comment]
ROCm is using llvm/clang 9.0.0. Can you provide the build.log?

**Comment by awenocur** [comment]
[build.log](https://github.com/justxi/rocm/files/3108259/build.log)

**Comment by justxi** [comment]
I think currently uninstalling "Z3" solved this for me.
If this helps, I could try to disalbe "Z3" detection.

**Comment by justxi** [comment]
Due to the fact, that this not related to the original issue and this seem to be resolved I close this.
Problem with "Z3" could be discussed here: https://github.com/justxi/rocm/issues/20
