### ISSUE TITLE
Installation directories / Duplicate files

### ISSUE THREAD

**Issue by davidrohr** [justxi/rocm#58]
Great, now /opt/rocm is fully gone. There are still some packages, where I am not so sure about the installation directories:

- rocm-device-libs: installs the bitcode files `*.bc` directly to /usr/lib, perhaps this should go to /usr/lib/bitcode?
- rocm-device-libs and rocr-runtime basically install the same header files (they have the same name, but different size), rocm-device-libs go directly to /usr/include and rocr-runtime goes to /usr/include/hsa. Not fully sure how to fix this, but I think these files should be present only once, and ideally in /usr/include/hsa
- roct-thunk-interface installs 2 more hsa headers, this time not overlapping with rocr-runtime. They go directly to /usr/include, perhaps /usr/include/hsa would be better, but not sure.
- rocm-comgr installs 2 `.pch` files to /usr/include. These are binary files, not headers. Probably shouldn't go to include.
- hcc still installs to /usr/lib/hcc/${PV}/, I'd get rid of the ${PV}

Please comment what you think on these.

**Comment by justxi** [comment]
That there are *.bc files in /usr/lib(64) I noticed too. I think there could be a more nice solution. But currently I am focusing on stability and usability. So that could be solved later. It must be guranteed that the libraries find these files.

I think the same applies to the header files.
I also saw that a libraries which depends on rocPRIM also install similar header files.

I don´t know it the pch files are used? These are "pre-compiled headers", aren´t they?

I would keep the version on hcc to make it possible to test other releases. And with the version it is equal to installation of the other toolchains.

**Comment by justxi** [comment]
@davidrohr

>     * rocm-device-libs: installs the bitcode files `*.bc` directly to /usr/lib, perhaps this should go to /usr/lib/bitcode?

Ebuild is in Gentoo Portage... we should discuess this with @candrews.
 
>     * rocm-device-libs and rocr-runtime basically install the same header files (they have the same name, but different size), rocm-device-libs go directly to /usr/include and rocr-runtime goes to /usr/include/hsa. Not fully sure how to fix this, but I think these files should be present only once, and ideally in /usr/include/hsa

Ebuild is in Gentoo Portage... we should discuess this with @candrews.
 
>     * roct-thunk-interface installs 2 more hsa headers, this time not overlapping with rocr-runtime. They go directly to /usr/include, perhaps /usr/include/hsa would be better, but not sure.

Ebuld is in Gentoo Portage... we should discuess this with @candrews.
 
>     * rocm-comgr installs 2 `.pch` files to /usr/include. These are binary files, not headers. Probably shouldn't go to include.

Ebuild is in Gentoo Portage... we should discuess this with @candrews.
 
>     * hcc still installs to /usr/lib/hcc/${PV}/, I'd get rid of the ${PV}

Please let us keep this, because it would result in much work and I think we will not use hcc if llvm-roc can be used to build hip.

**Comment by justxi** [comment]
@davidrohr 
@candrews

Due to the fact that most of the mentioned packages are in Gentoo portage now, any open issues should be discussed at https://bugs.gentoo.org/.
